import type { Metadata } from "next";
import "./globals.css";
import { montserrat } from "./fonts";
import { MenuHeader, SideMenu } from "./ui";
import { Footer } from './ui/footer/Footer';
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth.config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`} >
        <SessionProvider>
          {session ? (
            <>
              <MenuHeader />
              <SideMenu />
              {children}
            </>
          ) : (
            <>
              {children}
            </>
          )}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
